### ISSUE TITLE
Question VASP_interactive example

### ISSUE THREAD

**Issue by Alexyjones** [ulissigroup/al_mlp#31]
Dear Researchers, 

I tried to follow the example of VASP_interactive on online learning. However I struggled early, as the line:
 from al_mlp.atomistic_methods import replay_trajectory

leads to
ImportError: cannot import name 'replay_trajectory' from 'al_mlp.atomistic_methods' (.../.local/lib/python3.8/site-packages/al_mlp-0.1-py3.8.egg/al_mlp/atomistic_methods.py)

I had tried to install al_mlp using the setup.py routine. However I didn't see where the replay_trajectory function would be added, even in Github. 

Any help would be highly appreciated!

Alexander

**Comment by Alexyjones** [comment]
Hi, 

Thank you for your reply. I was trying to follow this example:

https://github.com/ulissigroup/vasp-interactive/blob/main/examples/ex10_mlp_online.py

I am trying to go for the example you pointed out, but still have some issues with the flare_pp package. Will come back on that later. 

Thanks again, 

Alexander

**Comment by Alexyjones** [comment]
Solved several issues, but sadly got stuck at this point. I didn't yet load the ocp data due to some issues, but I feel that might not be the problem here:

Traceback (most recent call last):
  File "online_ex.py", line 5, in <module>
    from al_mlp.ml_potentials.finetuner_ensemble_calc import FinetunerEnsembleCalc
  File "/home/alexander/.local/lib/python3.8/site-packages/al_mlp-0.1-py3.8.egg/al_mlp/ml_potentials/finetuner_ensemble_calc.py", line 1, in <module>
    from al_mlp.ml_potentials.finetuner_calc import FinetunerCalc
  File "/home/alexander/.local/lib/python3.8/site-packages/al_mlp-0.1-py3.8.egg/al_mlp/ml_potentials/finetuner_calc.py", line 5, in <module>
    from ocpmodels.preprocessing import AtomsToGraphs
  File "/home/alexander/Downloads/ocp/ocpmodels/preprocessing/__init__.py", line 8, in <module>
    from .atoms_to_graphs import AtomsToGraphs
  File "/home/alexander/Downloads/ocp/ocpmodels/preprocessing/atoms_to_graphs.py", line 12, in <module>
    from torch_geometric.data import Data
  File "/home/alexander/anaconda3/envs/ocp-models/lib/python3.8/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/home/alexander/anaconda3/envs/ocp-models/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/alexander/anaconda3/envs/ocp-models/lib/python3.8/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/alexander/anaconda3/envs/ocp-models/lib/python3.8/site-packages/torch_sparse/__init__.py", line 15, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
AttributeError: 'NoneType' object has no attribute 'origin'

**Comment by jmusiel** [comment]
I see, thanks for pointing that out. 

For this particular error my guess is that it is a problem with your torch install or your cuda install. Specifically torch_geometric. These are all prerequisites for the ocp package which is what is being used here. Can you try reinstalling them by following the instructions to install those packages for the ocp package?

The instructions are here: https://github.com/Open-Catalyst-Project/ocp

**Comment by Alexyjones** [comment]
Thanks for the hint, I got around that obstacle. Thanks for the pointer to torch_geometric. 

Now I hit another roadblock, where I am stuck: I looked into the files, but couldn't find that particular module as well. Would you have any hint, what I missed?


Traceback (most recent call last):
  File "online_ex.py", line 5, in <module>
    from al_mlp.ml_potentials.finetuner_ensemble_calc import FinetunerEnsembleCalc
  File "/home/alexander/.local/lib/python3.8/site-packages/al_mlp-0.1-py3.8.egg/al_mlp/ml_potentials/finetuner_ensemble_calc.py", line 1, in <module>
    from al_mlp.ml_potentials.finetuner_calc import FinetunerCalc
  File "/home/alexander/.local/lib/python3.8/site-packages/al_mlp-0.1-py3.8.egg/al_mlp/ml_potentials/finetuner_calc.py", line 13, in <module>
    from ocpmodels.datasets.trajectory_lmdb import data_list_collater
ModuleNotFoundError: No module named 'ocpmodels.datasets.trajectory_lmdb'

in that directory of ocp is only:

ls ~/Downloads/ocp/ocpmodels/datasets/
embeddings/      __init__.py      lmdb_dataset.py  __pycache__/

**Comment by jmusiel** [comment]
That was a bug caused by a change in one of our dependencies, we fixed it a little while ago, try pulling the latest version of al_mlp.

**Comment by Alexyjones** [comment]
Thanks for all your help. Now its just about finding a working gemnet config and I am good to go.

**Comment by jmusiel** [comment]
You should be able to find a working GemNet config in the Open Catalyst Project repo here: https://github.com/Open-Catalyst-Project/ocp/blob/main/configs/s2ef/all/gemnet/gemnet-dT.yml

Although you may have to change line 32 to match the path specific to your filesystem.

You will probably also want a pretrained OCP model file (called a checkpoint), you can find them here under the S2EF models (I recommend using "GemNet-dT All" as that is the best one right now): https://github.com/Open-Catalyst-Project/ocp/blob/main/MODELS.md
